spring:
  application:
    name: auth-service

server:
  port: 3000

keycloak:
  url: http://localhost:8180
  realm: jobify-realm
  client-id: backend
  client-secret: bayGzLbcnd4aZt0ylOKGXr1flCVluzCh
  admin:
    username: admin
    password: admin

mongodb:
  uri: mongodb://localhost:27017/nest

eureka:
  host: localhost
  port: 8761