spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: interview-service
              uri: lb://INTERVIEW-SERVICE
              predicates:
                - Path=/interview-service/**
              filters:
                - StripPrefix=1
            - id: ai-service
              uri: lb://AI-SERVICE
              predicates:
                - Path=/ai-service/**
              filters:
                - StripPrefix=1
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth-service/**
              filters:
                - StripPrefix=1
            - id: application-service
              uri: lb://APPLICATION-SERVICE
              predicates:
                - Path=/application-service/**
              filters:
                - StripPrefix=1
            - id: joboffer-service
              uri: lb://JOBOFFER-SERVICE
              predicates:
                - Path=/joboffer-service/**
              filters:
                - StripPrefix=1
            - id: career-advice
              uri: lb://CAREER-ADVICE
              predicates:
                - Path=/career-advice/**
              filters:
                - StripPrefix=1

          discovery:
            locator:
              enabled: true
              lower-case-service-id: true

server:
  port: 8888
  address: 0.0.0.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.loadbalancer: DEBUG
