spring:
  application:
    name: joboffer-service
  datasource:
    url: jdbc:mysql://localhost:3306/joboffer_db?createDatabaseIfNotExist=true
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        id:
          new_generator_mappings: false
          db_structure_naming_strategy: legacy
  cloud:
    discovery:
      enabled: true

server:
  port: 8082